runtime:      go111

main:         ./cmd
handlers:
- url:        /static/html
  static_dir: static/html

- url:        /static/css
  static_dir: static/css

- url:        /static/images
  static_dir: static/images


# All active conten handled by the app
- url:        /.*
  script:     auto
  secure:     always
